version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true" # For development testing simplicity, disable security
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  app:
    build: .
    container_name: customer-intelligence-app
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOST=opensearch
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  opensearch-data:
